name: Generate GitHub Stats

on:
workflow_dispatch:
schedule:
- cron: "0 0 * * *"

permissions:
contents: write

jobs:
generate-stats:
runs-on: ubuntu-latest

steps:
  - name: Checkout repository
    uses: actions/checkout@v4

  - name: Create profile directory
    run: mkdir -p profile

  - name: Generate GitHub Stats
    run: |
      curl -L \
      "https://github-readme-stats.vercel.app/api?username=ismail-chahboune&show_icons=true&theme=default&hide_border=true&count_private=true" \
      -o profile/stats.svg

  - name: Generate Top Languages
    run: |
      curl -L \
      "https://github-readme-stats.vercel.app/api/top-langs/?username=ismail-chahboune&layout=compact&hide_border=true&theme=default" \
      -o profile/top-langs.svg

  - name: Commit statistics
    run: |
      git config --local user.email "github-actions[bot]@users.noreply.github.com"
      git config --local user.name "github-actions[bot]"
      git add profile/stats.svg profile/top-langs.svg
      git diff --cached --quiet || git commit -m "Update GitHub statistics"
      git push
